name: example
description: "An example project to demonstrate the use of reko_mqtt_helper"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  connectivity_plus: ^6.0.5
  device_info_plus: ^10.1.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.2
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  get: ^4.6.6
  reko_mqtt_helper:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
